title: iCompanion
description: A companion app for UH Manoa's iLab
google_analytics:
show_downloads: false
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: true
  repository_url: https://github.com/i-companion/iCompanion
gems:
  - jekyll-mentions